import { EPDFBorderFlags, EPDFCellFlags, IPDFTemplate, PDFTemplateData } from './mrbau-pdf-lib.service';

export const ReviewSheetTemplate : IPDFTemplate = {
  title: 'Rechnungs-Prüfblatt',
  company: ['Firma', '{{mrba:companyStreet}}', '{{mrba:companyZipCode}}', '{{mrba:companyCity}}', '{{mrba:companyVatID}}'],
  lines : [
    { line:['Auftrags-Summe:','{auftragssumme}','Zusatz-Aufträge:','{zasumme}', 'Gesamt-Summe:', '{gesamtsumme}'], flags: [0, EPDFCellFlags.Right, 0, EPDFCellFlags.Right, 0, EPDFCellFlags.Right], cellBorder: [0,EPDFBorderFlags.Outline,0,EPDFBorderFlags.Outline,0,EPDFBorderFlags.Outline] },
    { extraSpaceY: 4},
    { line:['Übernahme am:','{uebernahmedate}', null, 'Mängelfreimeldung am:','{maengelfreimeldung}'], border: EPDFBorderFlags.Outline ,colWeight:[ 2, 2, 3, 3, 2], flags: [0, EPDFCellFlags.Right, 0, EPDFCellFlags.Right, EPDFCellFlags.Right] },
    { extraSpaceY: 4},
    { line:['BVH:','{bvh}', 'KT:','{kt}'], colWeight:[ 1, 8, 1, 2] , flags: [0, 0, EPDFCellFlags.Right, EPDFCellFlags.Right], border:EPDFBorderFlags.Upper },
    { line:['Gewerk:','{gewerk}'], colWeight:[ 1, 5], border:EPDFBorderFlags.Lower  },
    { extraSpaceY: 4},
    { line:['Rechnung','R-Nr.:', '{rechnungsnr}', 'Datum:','{rechnungsdatum}', 'Netto €', '{rechnungsbetragnetto}'], colWeight:[ 2, 1, 2, 2, 2, 1, 2], flags: [0, EPDFCellFlags.Right, 0, EPDFCellFlags.Right, 0, EPDFCellFlags.Right, EPDFCellFlags.Right], border: EPDFBorderFlags.Outline },
    { line:['Rechnungskorrektur', 'Netto €','{rechnungskorrekturnetto}'], colWeight:[ 9, 1, 2], flags: [0, EPDFCellFlags.Right, EPDFCellFlags.Right], border: EPDFBorderFlags.Outline },
    { line:['Korrigierte Rechnungssumme Netto', 'Netto €','{rechnungsbetragnettokorr}'], colWeight:[ 9, 1, 2], flags: [0, EPDFCellFlags.Right, EPDFCellFlags.Right], border: EPDFBorderFlags.Outline },
    { condition: "!isBauleistungsRechnung()", line:['Korrigierte Rechnungssumme Brutto', 'Brutto €','{rechnungsbetragbruttokorr}'], colWeight:[ 9, 1, 2], flags: [0, EPDFCellFlags.Right, EPDFCellFlags.Right], border: EPDFBorderFlags.Outline },
    { extraSpaceY: 4},
    { line:['Abzüge'], flags: [EPDFCellFlags.Oblique] },
    { line:['- nicht zordenbare Bauschäden', '{nzbauschaedenprozent}','% von','{rechnungsbetragnettokorr}','{nzbauschaedennetto}', null], colWeight:[ 4, 1, 1, 2, 2, 2], flags: [0,EPDFCellFlags.Right,0,0,EPDFCellFlags.Right,EPDFCellFlags.Right], border: EPDFBorderFlags.Outline },
    { line:['- direkte Bauschäden', '{bauschaedennetto}', null], colWeight:[ 8, 2, 2], flags: [0,EPDFCellFlags.Right,EPDFCellFlags.Right], border: EPDFBorderFlags.Outline },
    { line:['- Sonderabzüge', '{sonderabzuege}', null], colWeight:[ 8, 2, 2], flags: [0,EPDFCellFlags.Right,EPDFCellFlags.Right], border: EPDFBorderFlags.Outline },
    { line:['- Sonderabzüge in Prozent', '{sonderabzuegepercent}','% von','{rechnungsbetragnettokorr}','{sonderabzuegepercentnetto}', null], colWeight:[ 4, 1, 1, 2, 2, 2], flags: [0,EPDFCellFlags.Right,0,0,EPDFCellFlags.Right,EPDFCellFlags.Right], border: EPDFBorderFlags.Outline },
    { line:['Summe Abzüge', 'Netto €','{summeabzuegenetto}'], colWeight:[ 9, 1, 2], flags: [0,EPDFCellFlags.Right,EPDFCellFlags.Right], border: EPDFBorderFlags.Outline },
    { extraSpaceY: 4},
    { line:['Umlagekosten'], flags: [EPDFCellFlags.Oblique] },
    { line:['- Schuttbeseitigung', '{schuttprozent}','% von','{rechnungsbetragnettokorr}','{schuttnetto}', null], colWeight:[ 4, 1, 1, 2, 2, 2], flags: [0,EPDFCellFlags.Right,0,0,EPDFCellFlags.Right,EPDFCellFlags.Right], border: EPDFBorderFlags.Outline },
    { line:['- Baureinigung', '{reinigungprozent}','% von','{rechnungsbetragnettokorr}','{reinigungnetto}', null], colWeight:[ 4, 1, 1, 2, 2, 2], flags: [0,EPDFCellFlags.Right,0,0,EPDFCellFlags.Right,EPDFCellFlags.Right], border: EPDFBorderFlags.Outline },
    { line:['- Baustellen WC', '{wcprozent}','% von','{rechnungsbetragnettokorr}','{wcnetto}', null], colWeight:[ 4, 1, 1, 2, 2, 2], flags: [0,EPDFCellFlags.Right,0,0,EPDFCellFlags.Right,EPDFCellFlags.Right], border: EPDFBorderFlags.Outline },
    { line:['- Wasser', '{wasserprozent}','% von','{rechnungsbetragnettokorr}','{wassernetto}', null], colWeight:[ 4, 1, 1, 2, 2, 2], flags: [0,EPDFCellFlags.Right,0,0,EPDFCellFlags.Right,EPDFCellFlags.Right], border: EPDFBorderFlags.Outline },
    { line:['- Strom', '{stromprozent}','% von','{rechnungsbetragnettokorr}','{stromnetto}', null], colWeight:[ 4, 1, 1, 2, 2, 2],flags: [0,EPDFCellFlags.Right,0,0,EPDFCellFlags.Right,EPDFCellFlags.Right], border: EPDFBorderFlags.Outline },
    { line:['Summe Umlagekosten', 'Netto €','{sumumlage}'], colWeight:[ 9, 1, 2], flags: [0,EPDFCellFlags.Right,EPDFCellFlags.Right], border: EPDFBorderFlags.Outline },
    { extraSpaceY: 4},
    { line:['Geprüfte Rechnungssumme', 'Netto €','{sumnetto2}'], colWeight:[ 9, 1, 2], flags: [0,EPDFCellFlags.Right,EPDFCellFlags.Right], border: EPDFBorderFlags.Outline },
    { condition: "!isBauleistungsRechnung()", line:['MWSt {taxRate}%', '€','{ustsumnetto2}'], colWeight:[ 9, 1, 2], flags: [0,EPDFCellFlags.Right,EPDFCellFlags.Right], border: EPDFBorderFlags.Outline },
    { condition: "!isBauleistungsRechnung()", line:['Geprüfte Rechnungssumme Brutto', 'Brutto €','{brutto2}'], colWeight:[ 9, 1, 2], flags: [0,EPDFCellFlags.Right,EPDFCellFlags.Right], border: EPDFBorderFlags.Outline },
    { extraSpaceY: 4},
    { line:['Abzüglich Teilzahlungen Netto', 'Netto €','{teilznetto}'], colWeight:[9, 1, 2], flags: [0,EPDFCellFlags.Right,EPDFCellFlags.Right], border: EPDFBorderFlags.Outline },
    { condition: "!isBauleistungsRechnung()", line:['Abzüglich Teilzahlungen MWSt {{taxRate}}%', '€','{teilzmwst}'], colWeight:[ 9, 1, 2], flags: [0,EPDFCellFlags.Right,EPDFCellFlags.Right], border: EPDFBorderFlags.Outline },
    { condition: "!isBauleistungsRechnung()", line:['Abzüglich Teilzahlungen Brutto', 'Brutto €','{teilzbrutto}'], colWeight:[ 9, 1, 2], flags: [0,EPDFCellFlags.Right,EPDFCellFlags.Right], border: EPDFBorderFlags.Outline },
    { line:['Einbehalt / Gegenverrechnung', '€','{einbehalt}'], colWeight:[ 9, 1, 2], flags: [0,EPDFCellFlags.Right,EPDFCellFlags.Right], border: EPDFBorderFlags.Outline },
    { condition: "isTeilRechnung()", line:['Deckungsrücklass', '{deckungsruecklasspercent}','% von','{rechnungsbetragnettokorr}','€','{deckungsruecklass}'], colWeight:[ 5, 1, 1, 2, 1, 2], flags: [0,EPDFCellFlags.Right,0,0,EPDFCellFlags.Right,EPDFCellFlags.Right], border: EPDFBorderFlags.Outline },
    { condition: "!isTeilRechnung()", line:['Haftrücklass {haftruecklassLabel}', '{haftruecklasspercent}','% von','{rechnungsbetragnettokorr}','€','{haftruecklass}'], colWeight:[ 5, 1, 1, 2, 1, 2], flags: [0,EPDFCellFlags.Right,0,0,EPDFCellFlags.Right,EPDFCellFlags.Right], border: EPDFBorderFlags.Upper },
    { condition: "!isTeilRechnung()", line:[null, 'Laufzeit bis:', '{haftruecklassdate}',null], colWeight:[ 1, 2, 2, 7], border: EPDFBorderFlags.Lower },
    { extraSpaceY: 4},
    { line:['Zahlungsbetrag'], flags: [EPDFCellFlags.Oblique] },
    { line:['Offener Betrag' ,'Fälligkeit:','{datumnet}','€','{offenerbetrag}'], colWeight:[ 5, 2, 2, 1, 2], flags: [0,0,0,EPDFCellFlags.Right,EPDFCellFlags.Right], border: EPDFBorderFlags.Outline },
    { extraSpaceY: 4},
    { condition: "skonto1()", line:['Skonto', '{skontopercent1}','% von','{rechnungsbetragnettokorr}','{skonto1}', null], colWeight:[ 4, 1, 1, 2, 2, 2], flags: [0,EPDFCellFlags.Right,0,0,EPDFCellFlags.Right,EPDFCellFlags.Right], border: EPDFBorderFlags.Outline },
    { condition: "skonto1()", line:['Offener Betrag Skonto','Fälligkeit:','{datumskonto1}','€','{offenerbetragskonto1}'], colWeight:[ 5, 2, 2, 1, 2], flags: [0,0,0,EPDFCellFlags.Right,EPDFCellFlags.Right], border: EPDFBorderFlags.Outline },
    { condition: "skonto1()", extraSpaceY: 4},
    { condition: "skonto2()", line:['Skonto 2', '{skontopercent2}','% von','{rechnungsbetragnettokorr}','{skonto2}', null], colWeight:[ 4, 1, 1, 2, 2, 2], flags: [0,EPDFCellFlags.Right,0,0,EPDFCellFlags.Right,EPDFCellFlags.Right], border: EPDFBorderFlags.Outline },
    { condition: "skonto2()", line:['Offener Betrag Skonto 2','Fälligkeit:','{datumskonto2}','€','{offenerbetragskonto2}'], colWeight:[ 5, 2, 2, 1, 2], flags: [0,0,0,EPDFCellFlags.Right,EPDFCellFlags.Right], border: EPDFBorderFlags.Outline },
    { condition: "skonto2()", extraSpaceY: 4},
    { line:['SCHLUSSRECHNUNGSERKLÄRUNG:\nDurch seine firmenmäßige Unterfertigung erklärt sich der Auftragnehmer mit obigem Ergebnis der Schlussrechnung vorbehaltlos einverstanden. Er bestätigt, dass in dem überprüften und hier bezifferten Verdienstbetrag sämtliche Forderungen enthalten sind, welche aus diesem Bauprojekt zu stellen waren.',
            'Unterschrift'], fontSize: [8, 8], lineHeight: 12,  colWeight:[ 6, 1], cellBorder: [EPDFBorderFlags.Outline, EPDFBorderFlags.Outline,], flags: [EPDFCellFlags.Multiline, EPDFCellFlags.Centered] },
  ]
} as const;

export interface ReviewSheetData extends PDFTemplateData {
  auftragssumme : number,
  zasumme : number,
  gesamtsumme : number,
  uebernahmedate: Date
  maengelfreimeldung: Date,
  bvh : string,
  kt : string,
  gewerk: string,
  rechnungsnr : string,
  rechnungsdatum: string,
  rechnungsbetragnetto: number,
  rechnungskorrekturnetto: number
  rechnungsbetragnettokorr: number,
  rechnungsbetragbruttokorr: number,
  nzbauschaedenprozent: number,
  nzbauschaedennetto: number,
  bauschaedennetto: number,
  sonderabzuege : number,
  sonderabzuegepercent: number,
  sonderabzuegepercentnetto: number,
  summeabzuegenetto: number,
  schuttprozent: number,
  schuttnetto: number,
  reinigungprozent: number,
  reinigungnetto: number,
  wcprozent: number,
  wcnetto: number,
  wasserprozent: number,
  wassernetto: number,
  stromprozent: number,
  stromnetto: number,
  sumumlage: number,
  sumnetto2: number,
  ustsumnetto2: number,
  brutto2: number,
  taxRate: number,
  teilznetto: number,
  teilzmwst: number,
  teilzbrutto: number,
  einbehalt: number,
  deckungsruecklasspercent: number,
  deckungsruecklass: number,
  haftruecklasspercent: number,
  haftruecklass: number,
  haftruecklassLabel: string,
  haftruecklassdate: Date,
  datumnet: Date,
  offenerbetrag: number,
  skontopercent1: number,
  skonto1: number,
  datumskonto1: Date,
  offenerbetragskonto1: number,
  skontopercent2: number,
  skonto2: number,
  datumskonto2: Date,
  offenerbetragskonto2: number,
  isBauleistungsRechnung: boolean,
  isTeilRechnung: boolean
}
